#Documentaçao oficial
name: docker-login
run-name: Deploy to Login Docker by @${{ github.actor }}

on:
  push:
    branches: main #Set your workflow to run on push events to the main
  pull_request: #Set your workflow to run on pull_request events that target the main branch
    branches:
    - main  

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
