name: Evento de PullRequest

on:
  push:
   branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      -main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
